# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false

- task: CmdLine@2
  inputs:
    script: |
      projver=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: './build/libs/NVCLDataServices-$(projver).war'
    artifact: 'bootWARPackage'
    publishLocation: 'pipeline'