plugins {
	id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
	id 'java'
	id 'war'
}

group = 'org.auscope'
// Use release version from CI, otherwise use a local snapshot version
version = System.getenv('RELEASE_VERSION') ?: '2.3.3.x'


springBoot {
    buildInfo()
}

bootWar {
    archiveBaseName = 'NVCLDataServices'
    launchScript()
    from ('config/application.properties') {
        into 'WEB-INF/classes/'
    }
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

configurations.configureEach {
    exclude group: 'commons-logging', module: 'commons-logging'
}

dependencies {
    implementation platform("com.azure:azure-sdk-bom:1.3.8")
    implementation "com.azure:azure-storage-blob"
    implementation "com.azure:azure-identity"
    implementation "org.springframework.boot:spring-boot-starter-web"
	implementation "org.springframework.boot:spring-boot-starter-activemq"
	implementation "org.springframework.boot:spring-boot-starter-jdbc"
	implementation "org.springframework.boot:spring-boot-starter-quartz"
    implementation "org.springframework.boot:spring-boot-starter-mail"
    implementation "org.springframework.boot:spring-boot-starter-thymeleaf"
    implementation "org.apache.activemq:activemq-broker"
    implementation 'org.apache.activemq:activemq-kahadb-store'
    implementation "org.apache.activemq:activemq-spring"
    implementation "org.apache.activemq:activemq-client"
	implementation 'commons-io:commons-io:2.20.0'
	implementation 'org.jfree:jfreechart:1.0.19'
	implementation 'com.drewnoakes:metadata-extractor:2.19.0'
	implementation('com.opencsv:opencsv:5.10') { exclude group: 'commons-logging', module: 'commons-logging' }
	implementation 'org.springframework:spring-oxm'
    implementation 'com.oracle.database.jdbc:ojdbc11'
    implementation 'com.microsoft.sqlserver:mssql-jdbc'
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api'
    runtimeOnly 'org.glassfish.jaxb:jaxb-runtime'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'net.javacrumbs.json-unit:json-unit-assertj:4.1.0'
}

bootRun {
    jvmArgs = ['-Xmx2g']
}

test {
    useJUnitPlatform()
}
