package org.auscope.nvcl.server.service;

import javax.jms.JMSException;
import javax.jms.Message;
import org.springframework.jms.core.MessagePostProcessor;

public class SpringFrameworkJmsSender {

    /**
     * <code>MessagePostProcessor</code> in charge of holding a reference on the sent message.
     * <p>
     * Useful to retrieve the JMS properties that has been generated by the JMS Provider (e.g.
     * jmsMessageID ...)
     */
    public static class ReferenceHolderMessagePostProcessor implements MessagePostProcessor {
        protected Message sentMessage;

        /**
         * Return the sent message.
         */
        public Message getSentMessage() {
            return sentMessage;
        }

        public Message postProcessMessage(Message message) throws JMSException {
            // keep a reference on the messge
            this.sentMessage = message;
            return message;
        }

    }

 
}
